spring:
  application:
    name: my-good-service

      # seata分组,这里zxl跟file的service一致
  cloud:
    alibaba:
      seata:
        tx-service-group: zxl
  datasource:
    url: jdbc:mysql://localhost:3306/fescardubbo?serverTimezone=UTC
    username: root
    password: zhangxl
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


eureka:
  client:
    serviceUrl:
      defaultZone: http://@localhost:8761/eureka/
server:
  port: 8081

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zxl.entity